#!/usr/bin/env bash

# Set up the environment
source /autograder/source/helper_functions/trycatch.sh 
export ERR_RATE=100
export ERR_GENERIC=101
export student_user=student
test_runner=tester
# Note there's no checking on whether these work. If these fails there's no user friendly message displayed to students. Could probably add a trap command or similar to catch this



# Make users and permissions. Submitted code runs as student (set in Popen command in each test). Tasks touching the code run as tester 
try
(
    # Add user (with check that doesn't already exist)
    id -u "$student_user" &> /dev/null || adduser "$student_user" --no-create-home --disabled-password --gecos "" || throw $ERR_GENERIC
	id -u "$test_runner" &> /dev/null || adduser "$test_runner" --no-create-home --disabled-password --gecos "" || throw $ERR_GENERIC
	
	# Set permissions
    chgrp -R "$test_runner" /autograder/source || throw $ERR_GENERIC
	mkdir -p /autograder/student_code throw || $ERR_GENERIC
    chmod 777 /autograder/student_code || throw $ERR_GENERIC
    chmod 770 /autograder/source || throw $ERR_GENERIC
)
catch || {
    jq --null-input \
     --argjson score 0 \
     --arg output "ERROR: Issue encountered when setting up the test environment. This is an issue with the test system, not your submitted code. Contact a system administraor for assistance." \
     --arg output_format "simple_format" \
     --arg visibility: "visible" \
     --arg stdout_visibility: "visible" '$ARGS.named' \
     > /autograder/results/results.json
    exit 1
}



# Check the number of submissions hasn't exceeded the threshold. Only proceed if so.
# Bash doesn't like a redirect on the jq command for some reason here and so the writing to results.json is done in a seperate if statement for ease of getting working
try
(
	chmod u+x /autograder/source/helper_functions/rate_limiter.sh || throw $ERR_GENERIC
	limit_check=$(runuser -u "$test_runner" -- /autograder/source/helper_functions/rate_limiter.sh) || throw $ERR_GENERIC
	if ! [[ -z "$limit_check" ]]; then
	    jq --null-input \
         --argjson score 0 \
         --arg output "$limit_check" \
         --arg output_format "simple_format" \
         --arg visibility: "visible" \
         --arg stdout_visibility: "visible" '$ARGS.named' \
		> /autograder/results/results.json
		throw $ERR_RATE
	fi
)
catch || {
    if [[ "$exception_code" -eq $ERR_RATE ]] ; then
	   exit 0
	else
	    jq --null-input \
         --argjson score 0 \
         --arg output "ERROR: Issue encountered when checking the number of submissions made. This is an issue with the test system, not your submitted code. Contact a system administraor for assistance." \
         --arg output_format "simple_format" \
         --arg visibility: "visible" \
         --arg stdout_visibility: "visible" '$ARGS.named' \
          > /autograder/results/results.json
        exit 1
	fi
}



# Move the submission from the gradescope submission area to the working folder. Note assumes is called HelloWorld.c here. Set permissions so student's can't edit their submission. Note that this would then fail if there's already a submission that's been copied previously as write permission has been removed.
filename="HelloWorld.c"
try
(
    runuser -u "$test_runner" -- cp /autograder/submission/"$filename" /autograder/student_code/"$filename" || throw $ERR_GENERIC
	runuser -u "$test_runner" -- chmod o-w /autograder/student_code/"$filename" || throw $ERR_GENERIC
)
catch || {
    jq --null-input \
     --argjson score 0 \
     --arg output "ERROR: File could not be found. Check your submitted file has the correct file name. It needs to be exact." \
     --arg output_format "simple_format" \
     --arg visibility: "visible" \
     --arg stdout_visibility: "visible" '$ARGS.named' \
     > /autograder/results/results.json
    exit 1
}



# Run Python which runs the actual tests
# The test wrapper runs as root, as subprocess.Popen(user=...) can't switch user when started as tester
try
(
    cd /autograder/source || throw $ERR_GENERIC
	source /venv/bin/activate || throw $ERR_GENERIC
	python3.10 test_wrapper.py > /autograder/results/results.json || throw $ERR_GENERIC
	deactivate || throw $ERR_GENERIC
)
catch || {
    jq --null-input \
     --argjson score 0 \
     --arg output "ERROR: Test suite not run. This is most likely an issue with permissions, e.g. using too much memory causing the test suite to error out." \
     --arg output_format "simple_format" \
     --arg visibility: "visible" \
     --arg stdout_visibility: "visible" '$ARGS.named' \
    > /autograder/results/results.json	
	exit 1
}